### ISSUE TITLE
Follow up on using SVGXML in MenuButton

### ISSUE THREAD

**Issue by rurikoaraki** [microsoft/fluentui-react-native#1000]
#### Platform
- [ ] iOS
- [ ] macOS
- [x] win32
- [ ] windows
- [ ] android
 
#### Describe the feature that you would like added

From https://github.com/microsoft/fluentui-react-native/pull/990#discussion_r704627035:

Could we do something like what @lenahong did in ContextualMenu, specify this as "SVGXML" and just pass the full XML instead of needing function that returns JSX? That might get around the test app freezing.

I mention to see if we can keep the "endIcon" prop and also use an inline svg

_Originally posted by @Saadnajmi in https://github.com/microsoft/fluentui-react-native/pull/990#discussion_r704627035_

Seems like we need to figure out why colors didn't work with this approach to be able to be consistent with ContextualMenu.

#### What component or utility would this be added to

MenuButton

#### Have you discussed this feature with our team, and if so, who

@ValentinaKozlova , @Saadnajmi

**Comment by Saadnajmi** [comment]
You got the magical #1000 :')
