### ISSUE TITLE
Investigate using yarn 3

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/fluentui-react-native#1145]
yarn 3 is out, and supports a plugin to let react-native projects continue to work as expected with node_modules and all. Some improvements should be potentially better workspace/monorepo management, and faster build times. 

Our partner's repository react-native-test-app has already done this successfully: https://github.com/microsoft/react-native-test-app/pull/429

More info about yarn 3 here: https://dev.to/arcanis/yarn-3-0-performances-esbuild-better-patches-e07

**Comment by rurikoaraki** [comment]
Done with #2980
