### ISSUE TITLE
Bump @office-iss/rex-win32

### ISSUE THREAD

**Issue by rurikoaraki** [microsoft/fluentui-react-native#1162]
### Platform

- [ ] iOS
- [ ] macOS
- [X] win32
- [ ] windows
- [ ] android

### Describe the feature that you would like added

We should probably bump our version of @office-iss/rex-win32 to a build that includes the change to RN 0.64 in Office.

**Comment by rurikoaraki** [comment]
FYI to @PPatBoyd and @samuelfreiberg

**Comment by PPatBoyd** [comment]
consideration for long term; evergreen rex-win32 in furn
