### ISSUE TITLE
Failed prop type: Invalid prop 'color' supplied to 'Text' when trying the sample code with Checkbox from README.md

### ISSUE THREAD

**Issue by jakobpn** [microsoft/fluentui-react-native#1226]
### 

- [ ] I am willing to submit a PR to fix

### Requested priority

Normal

### Package version(s)

0.27.0

### Platform

- [ ] iOS
- [ ] macOS
- [ ] win32
- [ ] windows
- [X] android

### Please provide a reproduction of the bug

When I try the sample code from README.md, I get the following error:

<img width="275" alt="image" src="https://user-images.githubusercontent.com/13109307/145280776-eaebc865-e1d0-4aaf-a8ca-415302162bf3.png">

### Actual behavior

-

### Expected behavior

-

**Comment by rurikoaraki** [comment]
Android checkbox is unable to run without a ThemeProvider, which is a bug. We should fix the default theme to have the missing entries.

Workaround supplied is to use a ThemeProvider.

**Comment by rurikoaraki** [comment]
Fixed with #1309
