### ISSUE TITLE
[Fluent Tester] '@uifabricshared/build-native@^0.1.1' is not in the npm registry

### ISSUE THREAD

**Issue by jakobpn** [microsoft/fluentui-react-native#1232]
### 

- [ ] I am willing to submit a PR to fix

### Requested priority

Normal

### Products/applications affected

Fluent Tester app

### Package version(s)

0.27.0

### Platform

- [ ] iOS
- [ ] macOS
- [ ] win32
- [ ] windows
- [X] android

### Please provide a reproduction of the bug

1. Git clone https://github.com/microsoft/fluentui-react-native
2. Change directory to .\fluentui-react-native\apps\fluent-tester
3. npm install

### Actual behavior

npm ERR! 404 Not Found - GET https://registry.npmjs.org/@uifabricshared%2fbuild-native - Not found
npm ERR! 404
npm ERR! 404  '@uifabricshared/build-native@^0.1.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'fluent-tester'

also getting...

npm ERR! 404 Not Found - GET https://registry.npmjs.org/@fluentui-react-native%2feslint-config-rules - Not found
npm ERR! 404
npm ERR! 404  '@fluentui-react-native/eslint-config-rules@^0.1.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'fluent-tester'

### Expected behavior

npm install would complete without errors

**Comment by rurikoaraki** [comment]
Hi @jakobpn, we use yarn at the root level to install all of our dependencies. @uifabricshared/build-native is built as part of this repo.

Please see https://github.com/microsoft/fluentui-react-native/tree/master/apps/android for instructions on how to run the Android tester app.

@lenahong FYI

**Comment by jakobpn** [comment]
Thank You @rurikoaraki! This helped me get the fluent-tester app running.

**Comment by rurikoaraki** [comment]
Hey @jakobpn, I'm going to close this issue as I think you're unblocked. Please reopen if this is still causing you issues when launching the app.
