### ISSUE TITLE
[Win32] Icon size for the Button doesn't match the design

### ISSUE THREAD

**Issue by ValentinaKozlova** [microsoft/fluentui-react-native#1237]
### 

- [ ] I am willing to submit a PR to fix

### Package version(s)

0.27.0

### Platform

- [ ] iOS
- [ ] macOS
- [X] win32
- [ ] windows
- [ ] android

### Please provide a reproduction of the bug

1. Open ExperimentalButton page in the Tester

### Actual behavior

Size of icons for different sizes is incorrect
![image](https://user-images.githubusercontent.com/11574680/145606253-bc0b63b8-f07b-488b-8641-514286d30af5.png)

s - 16x16
m - 16x16
l - 20x20

### Expected behavior

s - 20x20, compound - 40x40
m - 20x20, compound - 40x40
l - 24x24, compound - 48x48

**Comment by rurikoaraki** [comment]
@ValentinaKozlova The actual icon in the redlines aligns with what we have. The redlines that are supplied by web include the 2px padding that is automatically included as part of a Fluent icon as part of its size. So the 20x20 icon in the redlines is actually a 16x16 icon with 2px padding (which gives 20px total height/width), etc. I've double checked this with design.

Compound button icons haven't been implemented yet though.

**Comment by ValentinaKozlova** [comment]
> @ValentinaKozlova The actual icon size in the redlines aligns with what we have. The redlines that are supplied by web include the 2px padding that is automatically included as part of a Fluent icon as part of its size. So the 20x20 icon in the redlines is actually a 16x16 icon with 2px padding (which gives 20px total height/width), etc. I've double checked this with design.
> 
> Compound button icons haven't been implemented yet though.

Thank you Ruriko, I'm closing the bug
