### ISSUE TITLE
[Win32] Button in HC mode doesn't match the design

### ISSUE THREAD

**Issue by ValentinaKozlova** [microsoft/fluentui-react-native#1242]
### 

- [ ] I am willing to submit a PR to fix

### Requested priority

Normal

### Package version(s)

0.27.0

### Platform

- [ ] iOS
- [ ] macOS
- [X] win32
- [ ] windows
- [ ] android

### Please provide a reproduction of the bug

1. Switch PC to High contrast mode
2. Run `yarn bundle`
3. Run `yarn run-win32` (don't use web debugger)
4. Select "Office" in Theme dropdown in opened Fluent Tester.  

### Actual behavior

**Default button:**

1. White border on hover and pressed:
![image](https://user-images.githubusercontent.com/11574680/145829636-d7ac8e7c-aacd-4179-9aa3-5eb49d88ce33.png)
2. Focused state doesn't match the design:
![image](https://user-images.githubusercontent.com/11574680/145830231-b38e7465-f803-468b-9c5f-4512c76e9003.png)
3. Spinner for Loading button has incorrect color

**Primary button:**
1. Rest state:
![image](https://user-images.githubusercontent.com/11574680/145830706-e05c6908-d042-4f75-b037-382cdf5180b5.png)
2. Toggle pressed:
![image](https://user-images.githubusercontent.com/11574680/145830858-fe66201f-d8e7-40df-92fd-be0bfeb01117.png)
3. Focused state:
![image](https://user-images.githubusercontent.com/11574680/145831153-b4c77183-af9e-40f1-a577-700906be1357.png)

### Expected behavior

**Default button:**
1. There shouldn't be white border
2. Focus state:
![image](https://user-images.githubusercontent.com/11574680/145830524-376087d1-43eb-4262-895b-737d7b95ceeb.png)
3. Spinner for Loading button
![image](https://user-images.githubusercontent.com/11574680/145830628-a9f6fb44-1db7-4cf8-95a5-83a632f66df8.png)

**Primary button:**
1. Rest state:
![image](https://user-images.githubusercontent.com/11574680/145830780-34ab6f84-2dcf-42b3-b087-167248aa2d8a.png)
2. Toggle pressed should have dark font color (neutral foreground interactive token)
3. Focused state:
![image](https://user-images.githubusercontent.com/11574680/145831173-40a429b8-9b6b-4c22-ba91-a8320b5c60ce.png)

**Comment by rurikoaraki** [comment]
@ValentinaKozlova I would check with Sunmin before making these changes. Web HC and Win32 HC behave in different ways, so we shouldn't blindly follow the web HC spec.
