### ISSUE TITLE
ContextualMenuItem/SubmenuItem shouldn't override onMouseEnter/onMouseLeave

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/fluentui-react-native#1267]
Inside SubmenuItem, we "highlight" the menu item by setting focus on it. 

We want onMouseEnter to fire right away to set focus, and then Pressable's onHoverIn to fire after a delay to show the submenu. To achieve this, we override the onMouseEnter handler returned by useAsPressable, and replace it with our own. Inside our own onMouseEnter handler, we call useAsPressable's onMouseEnter handler, which incorporates the delay passed to delayHoverIn.  In the future, we can avoid needing to override onMouseEnter by handling submenu rendering internally rather than depending on the client to conditionally render it with onHoverIn.

**Comment by rurikoaraki** [comment]
@SaadNajmi Do you think this is ok to close out in lieu of Menu V1?

**Comment by Saadnajmi** [comment]
Yep
