### ISSUE TITLE
Logging bug isn't an option when logging an issue

### ISSUE THREAD

**Issue by rurikoaraki** [microsoft/fluentui-react-native#1315]
When you go to submit a new issue to this repo, the options don't show a "Report a bug" button, even though we have a template for it.

#1053 made some changes to our issues infrastructure, maybe the bug template has a problem with it? I didn't see anything obvious, though. @chrisglein and @Saadnajmi as FYI

**Comment by Saadnajmi** [comment]
Looks like GitHub recognized the issue


![image](https://user-images.githubusercontent.com/6722175/148288009-d2920c47-34fa-472f-92fa-f39dc09777e7.png)

**Comment by rurikoaraki** [comment]
> Looks like GitHub recognized the issue
> 
> ![image](https://user-images.githubusercontent.com/6722175/148288009-d2920c47-34fa-472f-92fa-f39dc09777e7.png)

🤦‍♀️idk why I didn't try that
