### ISSUE TITLE
Disabled button should not be selectable

### ISSUE THREAD

**Issue by chiuam** [microsoft/fluentui-react-native#1321]
### Willing to submit a PR to fix?

- [ ] I am willing to submit a PR to fix

### Requested priority

Normal

### Package version(s)

0.27.0

### Platform

- [ ] iOS
- [X] macOS
- [ ] win32
- [ ] windows
- [ ] android

### Please provide a reproduction of the bug

Launch experimental button in the test app, press the disabled button.

### Actual behavior

Button gets keyboard focus and background color changes to the pressed state color

https://user-images.githubusercontent.com/67026167/148422943-5b53be3d-9d56-4713-9479-53e38b24dd50.mov

### Expected behavior

Not sure if it should get keyboard focus, but it should not alter its state and visuals.

**Comment by rurikoaraki** [comment]
I thought I fixed this with https://github.com/microsoft/fluentui-react-native/pull/1272? Did it not work?

**Comment by Saadnajmi** [comment]
> I thought I fixed this with #1272? Did it not work?

We looked at it, and I'm convinced it's a bug in react-native-macos. calling `ref.current.focus()` will focus regardless of the `focusable` state.
