### ISSUE TITLE
Windows Tester won't load test pages

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/fluentui-react-native#1375]
I ran the windows test app, and tried to open both "ActivityIndicator" and "Button" test page, and got this error:

![Screenshot 2022-01-25 152808](https://user-images.githubusercontent.com/6722175/151063150-093af569-402f-4ff6-953c-28eacc8321ea.jpg)

**Comment by rurikoaraki** [comment]
Yeah... This is a manifestation of #1046. We should probably just stop using experimental-text as part of the header. The app works fine in a release bundle though, so you can also opt to reload from JS Bundle from the top left menu.

**Comment by rurikoaraki** [comment]
Fixed with #1809
