### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by rtorr** [microsoft/fluentui-react-native#1405]
### Platform

- [ ] iOS
- [ ] macOS
- [X] win32
- [X] windows
- [ ] android

### Describe the feature that you would like added

I would like to propose adding a project roadmap to this repository so that the community can better understand priority and timeline.

**Comment by rurikoaraki** [comment]
Hey @rtorr! Thanks for interest in FURN!

We track our progress on our work using other tooling as we think it suits our scheduling needs better. However, we recently added https://github.com/microsoft/fluentui-react-native/wiki/Updates-Coming-to-FURN-(02-11-2022) which hopefully answers some of your questions about the project roadmap. If you have any other questions please feel free to comment here.

**Comment by rtorr** [comment]
Rad, thank you!
