### ISSUE TITLE
All Exported Controls Should Export Examples

### ISSUE THREAD

**Issue by tkamireh** [microsoft/fluentui-react-native#15]
All exported controls from packages like experimental-web-controls should also export example usages of the controls. This makes it easier to map those directly into demo apps and more fully document them. 

A potential folder structure may look something like

-- Controls-Package
---- Example-Control
------ index.ts
------ examples
------- base
------ styles
------ types
------ example-control.tsx
------ tests

**Comment by FalseLobster** [comment]
I'm not sure this is really relevant any more? If anything we should investigate storybook.
