### ISSUE TITLE
RN .66 upgrade for FURN

### ISSUE THREAD

**Issue by ejlayne** [microsoft/fluentui-react-native#1501]
### Platform

- [X] iOS
- [X] macOS
- [X] win32
- [ ] windows
- [X] android

### Describe the feature that you would like added

We need to upgrade the react-native version to .66 in Fluent UI React Native, based on the upgrades happening in Microsoft Office code.

### What component or utility would this be added to

This is a dependency upgrade.

### Have you discussed this feature with our team, and if so, who

@samuelfreiberg @PPatBoyd @ksiler

**Comment by rurikoaraki** [comment]
Fixed with #1809
