### ISSUE TITLE
Shadow unable to pass Jest tests

### ISSUE THREAD

**Issue by nabil-k** [microsoft/fluentui-react-native#1845]
### Willing to submit a PR to fix?

- [ ] I am willing to submit a PR to fix

### Products/applications affected

Shadow Component, after FURN update to RN 0.66

### Package version(s)

@fluentui-react-native/experimental-shadow (0.2.2)

### Platform

- [ ] iOS
- [ ] macOS
- [ ] win32
- [ ] windows
- [ ] android

### Please provide a reproduction of the bug

To see the issue add   ` "test": "fluentui-scripts jest"` to the Shadow's `package.json` under scripts and run `yarn test` at the components root folder. Or just run `yarn buildci`

### Actual behavior

Error you'll see:
ERR!  FAIL  src/__tests__/Shadow.test.tsx
ERR!   ● Shadow component tests › Shadow (depth=2)
ERR!
ERR!     Invariant Violation: __fbBatchedBridgeConfig is not set, cannot invoke native modules
ERR!
ERR!       at invariant (../../../node_modules/invariant/invariant.js:40:15)
ERR!       at Object.<anonymous> (node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:181:3)
ERR!       at Object.<anonymous> (node_modules/react-native/Libraries/TurboModule/TurboModuleRegistry.js:11:23)

### Expected behavior

Test should pass.

**Comment by rurikoaraki** [comment]
I think this is fixed so I'm going to close
