### ISSUE TITLE
Create Demo app to include in readme/getting started instructions

### ISSUE THREAD

**Issue by ejlayne** [microsoft/fluentui-react-native#189]
The library needs a demo app to include in the readme/getting started instructions. The purpose of this demo app is to give folks a quick way to download and use our package in a prepackaged environment, for people that don't have an existing react-native app to add our package to. Examples:

- https://developer.microsoft.com/en-us/fluentui#/get-started#option-1-quick-start
- https://github.com/microsoft/fluentui-apple/blob/master/ios/README.md#demo-app

**Comment by tanaypratap** [comment]
@ejlayne would this mean that we create 4 demo apps: iOS, Android, Windows, macOS?

**Comment by espipj** [comment]
Hey! I'm happy to help with this or any other related stuff if someone can point me in the right direction 😄

**Comment by Saadnajmi** [comment]
Hello, we have demo apps for windows, win32, iOS, macOS, and android under the apps. I'm pretty sure we closed this with #463 #464 and #473
