### ISSUE TITLE
Switch Android CI Pipeline to `ubuntu-latest`

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/fluentui-react-native#1905]
Fallout from #1535 

We use the VM image `macOS-11` to run the "Android PR" ADO job in our pipeline. As was pointed out, `ubuntu-latest` is much much faster, so we should switch the job to use that. When I did that, the check hung. I assume this is because we're using a custom bash script. Related, we could probably also switch our check to just be a `grade build` invocation, similar to what react-native-test-app does in their CI.

**Comment by ayush547** [comment]
The issue is that the Android Emulator is currently available only for [hosted macOS agents](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/android?view=azure-devops#test-on-the-android-emulator).

**Comment by Saadnajmi** [comment]
Thanks for the update! Closing
