### ISSUE TITLE
Incorrect instructions for Fluent-Tester

### ISSUE THREAD

**Issue by NikoAri** [microsoft/fluentui-react-native#194]
https://github.com/microsoft/fluentui-react-native/tree/master/apps/fluent-tester

Current instructions:
Then go into apps\fluent-tester folder:
    cd apps\fluent-tester
Build the FluentUI Tester bundle:
    yarn bundle
Launch the FluentUI Tester app:
    yarn run-win32

But they should be cd apps\fluent-tester\win32

**Comment by dotnetjunky** [comment]
Feel free to submit a PR :) This is open source.

**Comment by NikoAri** [comment]
Thanks, will submit PR with doc fixes...

**Comment by ejlayne** [comment]
I've submitted a PR that addresses this. https://github.com/microsoft/fluentui-react-native/pull/473 Closing, but please let us know if you have any other issues or feedback.
