### ISSUE TITLE
In FluentUI-Tester App Options Web Debugger and Live Reload don't function

### ISSUE THREAD

**Issue by NikoAri** [microsoft/fluentui-react-native#195]
Repro:

1. cd apps\win32
1. yarn bundle
1. yarn run-win32
   (FluentUI Tester App Appears)
1. Click small rectangular button in top right
   (Debug menu appears)
1. Check Use Web Debugger CheckBox
   (App crashes)

Note:
Use Live Reload also doesn't work, but there is no crash

**Comment by dotnetjunky** [comment]
I believe @JasonVMo has resolved this issue?

**Comment by NikoAri** [comment]
It would be nice for someone to take a closer look at this overall experience.

1. yarn start-win32-web

produces following error:
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Error!

Program: ...eact-native2\node_modules\@office-iss\rex-win32\ReactTest.exe

abort() has been called

(Press Retry to debug the application)

---------------------------
Abort   Retry   Ignore   
---------------------------


2. yarn start-win32
Allows "Live Reload" and "Web Debug" options
Selecting Live Reload is ignored, selecting Web Debug crashes the app

I would argue that "Live Reload" and "Web Debug" options should be disabled when App is NOT running with Web Debugger.

**Comment by dotnetjunky** [comment]
Oh maybe you can help debug it, since you're familiar with how ReactTest works? 

Live Reload can be used independently of web debugger. There's no reason to disable it. 
The Web Debug option is to allow you to turn it on or off after you've launched the app.

**Comment by NikoAri** [comment]
No, I'm not so familiar with this area. My worry is that this can affect other future components that consume FluentUI

**Comment by rurikoaraki** [comment]
This should be working. Closing out.
