### ISSUE TITLE
fluentui-react-native/stack doesn't exist on NPM

### ISSUE THREAD

**Issue by rychomis** [microsoft/fluentui-react-native#198]
Hello, I'm trying to use some snippets from the tester code but I can't seem to find where the fluentui-react-native/stack exists

**Comment by ejlayne** [comment]
Hi @rychomis, it is a known issue that Stack is not being exported via npm. We are currently only using it internally and as part of the Fluent Tester app. For code examples, please see our [Fluent UI control documentation](https://developer.microsoft.com/en-us/fluentui#/controls/crossplatform), as we have removed references to Stack in this examples. Please let us know if you have any additional questions.

**Comment by FalseLobster** [comment]
We've exported Stack for now, but it's in a bit of a buggy state.
