### ISSUE TITLE
Is there plans to support drop downs?

### ISSUE THREAD

**Issue by rychomis** [microsoft/fluentui-react-native#202]
Is there plans to support drop downs soon?

**Comment by dotnetjunky** [comment]
Can you elaborate? Is there a specific type of drop down you are looking for? Is it a ComboBox, or something else?

**Comment by rychomis** [comment]
ya something similar to a combo box

**Comment by dotnetjunky** [comment]
I think sooner or later we'll definitely want to add combo box control because it's a very common control and the web Fluent UI library does provide it.

However, I don't know an exact timeline for it.

@ejlayne

**Comment by Saadnajmi** [comment]
@rychomis Both macOS and win32 have support for MenuButton, which I think suits this request. For questions about the win32 control, you can ask @ValentinaKozlova , and for the macOS control you can reach out to me. I'll close this issue now.
