### ISSUE TITLE
Win32 Tester App can't change color theme with system color setting

### ISSUE THREAD

**Issue by maggch97** [microsoft/fluentui-react-native#2042]
### Willing to submit a PR to fix?

- [ ] I am willing to submit a PR to fix

### Package version(s)

latest git

### Platform

- [ ] iOS
- [ ] macOS
- [X] win32
- [ ] windows
- [ ] android

### Please provide a reproduction of the bug

![image](https://user-images.githubusercontent.com/23057110/186870396-3a3551e1-2d34-41d6-a3f3-21b9cee11479.png)

The tester color theme is Auto defalut. When I set my system color to dark, the tester color is not changed.

I think this bug is not caused by the react native's hard code light when debug.

**Comment by rurikoaraki** [comment]
Hi @maggch97, instructions for testing the themes on win32 can be found here: https://github.com/microsoft/fluentui-react-native/blob/main/docs/pages/Testing/TestingThemesWin32.md
If you have any other questions feel free to comment on this issue and we can help you out.

**Comment by rurikoaraki** [comment]
This behavior is by design due to how Office theming is structured,
