### ISSUE TITLE
Build 2020 Feedback Thread - Fluent UI React Native

### ISSUE THREAD

**Issue by ejlayne** [microsoft/fluentui-react-native#206]
Welcome Build 2020 participants! Did you get a chance to try out the Fluent UI React Native library 
or watch our Build 2020 talk? If so, we want to hear your feedback! The library is still in its early stages, but we wanted to show developers the direction we're taking things, and get early feedback on how we can make this even more useful to you moving forward.

Feel free to leave feedback on any of the following (and please keep feedback constructive and respectful):
- Likes
- Dislikes
- Bugs
- Areas for improvement

Thank you,
The Fluent UI React Native team

**Comment by FalseLobster** [comment]
@ejlayne any objections to me closing this one out?

**Comment by FalseLobster** [comment]
Fun fact, the repo got 100 new stars after our Build announcement.  Let's not disappoint :)
