### ISSUE TITLE
Windows Button incorrectly styled

### ISSUE THREAD

**Issue by ejlayne** [microsoft/fluentui-react-native#211]
According to [Fluent design website](https://developer.microsoft.com/en-us/fluentui#/controls/crossplatform/button), the Windows Button should look like this:

![image](https://user-images.githubusercontent.com/508395/82357571-2875d880-99ba-11ea-92e7-8176caa838ec.png)

But currently, it looks like this:

![image](https://user-images.githubusercontent.com/508395/82357904-9ae6b880-99ba-11ea-953f-7debd0c251e5.png)

Creating this issue to track this inconsistency. Please let me know if you have any questions.

**Comment by Saadnajmi** [comment]
Was wondering about this as well! It seemed like the button style was a holdover from an older office UI Fabric, and doesn't match our other platforms on FluentUI. Thanks @ejlayne 🙂

**Comment by Brouilles** [comment]
Same. I have the following (see screenshot).
I have failed a step? (With React Native For Windows).

![image](https://user-images.githubusercontent.com/1573282/112022898-ffbaf400-8b32-11eb-8c31-2ea26f2bd991.png)

**Comment by chrisglein** [comment]
Is this fixed? This is what I see:
![image](https://user-images.githubusercontent.com/26607885/228996907-a5ef6375-d196-4a41-ad27-5aafccf7d122.png)

**Comment by Saadnajmi** [comment]
Yep! Fixed now.
