### ISSUE TITLE
Configure Aliasing to Avoid Relative Path Madness

### ISSUE THREAD

**Issue by tkamireh** [microsoft/fluentui-react-native#221]
#### Platform
- [x] iOS
- [x] macOS
- [x] win32
- [x] windows
- [x] android
 
#### Describe the feature that you would like added
Bundle configs should be set up to avoid long relative path imports.

#### What component or utility would this be added to
Any package where relative path importing is long

**Comment by rurikoaraki** [comment]
I don't think this is particularly an issue in our repo, since we import things by referring to the package it comes from. Let me know if you still think this is an issue, and we can discuss it here.
