### ISSUE TITLE
SVG Tests Broken - Bundling Transform Doesn't Work

### ISSUE THREAD

**Issue by tkamireh** [microsoft/fluentui-react-native#267]
### Environment Information

- **Package version(s)**: (fill this out, include which package manager you're using)
- **OS version**: (fill this out if relevant)

- **Platform**:
  - [ ] iOS
    - **Xcode version**:
  - [ ] macOS
    - **Xcode version**:
  - [x] win32
  - [?] windows
  - [?] android

### Please provide a reproduction of the bug:

Running yarn run-win32 from apps/win32 and clicking the SVG test page

#### Actual behavior:
Results in an assert and failure to render the SVGs

#### Expected behavior:
Should not assert, seems like a bundling transform isn't being run.

### Priorities and help requested:
No, assigning to @warren-ms 

Requested priority: (Blocking, High, Normal, Low)
Low

Products/applications affected: (if applicable)
Potential impact if customers are using SVGs via this broken pathway? They should be aware of the proper bundling transforms required for these code paths to work correctly.

**Comment by tkamireh** [comment]
@warren-ms  can you assign yourself please? Having trouble setting assignee

**Comment by warren-ms** [comment]
Hmm I don't seem to be able to assign it to me. I might not have permissions. Do you know who manages the repo permissions?
________________________________

**Comment by tkamireh** [comment]
weird, it works now
