### ISSUE TITLE
FabricTester should be FluentTester

### ISSUE THREAD

**Issue by gulnazsayed** [microsoft/fluentui-react-native#281]
### Environment Information

- **Platform**:
  - [x] iOS
    - **Xcode version**:
  - [x] macOS
    - **Xcode version**:
  - [x] win32
  - [x] windows
  - [ ] android

#### Actual behavior:

In testers' index.tsx files:

``` import * as React from 'react';
import {AppRegistry} from 'react-native';
import {ThemeProvider} from '@uifabricshared/theming-react-native';
import {FabricTester, customRegistry} from '@fluentui-react-native/tester';

const FluentTester = props => {
  return (
    <ThemeProvider registry={customRegistry}>
      <FabricTester {...props} />
    </ThemeProvider>
  );
}; 
```

In apps\fluent-tester\src\RNTester\FabricTester.tsx:
``` ...
export const FabricTester: React.FunctionComponent<IFabricTesterProps> = (props: IFabricTesterProps) => {
...
```

#### Expected behavior:

``` import * as React from 'react';
import {AppRegistry} from 'react-native';
import {ThemeProvider} from '@uifabricshared/theming-react-native';
import {FluentTester, customRegistry} from '@fluentui-react-native/tester';

const FluentTester = props => {
  return (
    <ThemeProvider registry={customRegistry}>
      <FluentTester {...props} />
    </ThemeProvider>
  );
}; 
```

### Priorities and help requested:

Are you willing to submit a PR to fix? Might be better for someone else to take a look as this might break several testers but I'd be happy to help!

Requested priority: Normal/Low

Products/applications affected: FluentUI Testers

**Comment by JasonVMo** [comment]
Agreed, we should remove references to fabric when we get a chance.

**Comment by JasonVMo** [comment]
Submitting a PR would be great. Maybe call that FluentTests or FluentTesterCore or something like that. Alternatively call it FluentTester and then use import as syntax to avoid the collision.
