### ISSUE TITLE
Deprecate "branded" token variants

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/fluentui-react-native#3156]
From a partner team:
> Color token naming is not consistent between platforms at times ....for example Android uses "
**brand**BackgroundColor" vs iOS which uses "**branded**BackgroundColor". You can see this in
ButtonColorTokens.ts (
[Link](https://github.com/microsoft/fluentui-react-native/blob/main/packages/components/Button/src/ButtonColorTokens.ts)
) vs ButtonColorTokens.Android.ts(
[Link](https://github.com/microsoft/fluentui-react-native/blob/main/packages/components/Button/src/ButtonColorTokens.android.ts)
) ... I was testing the Button with 'Primary' appearance

The "branded" tokens are form the older ramp, and should not be used for ButtonV1. We should remove their uses and mark them deprecated.

**Comment by lenahong** [comment]
[https://github.com/microsoft/fluentui-react-native/pull/3184](url)

The above pr removes deprecated color token usage from v1 components
