### ISSUE TITLE
NormalPeoplePicker sometimes not returning persona text after user selected one item from suggestion list

### ISSUE THREAD

**Issue by yulahyulah** [microsoft/fluentui-react-native#3200]
### Willing to submit a PR to fix?

- [ ] I am willing to submit a PR to fix

### Requested priority

Normal

### Package version(s)

"@fluentui/react": "8.97.2"

### Platform

- [ ] iOS
- [ ] macOS
- [ ] win32
- [X] windows
- [ ] android

### Please provide a reproduction of the bug

we cannot repro this issue by our own but noticed it from our logs which means some real customers have seen this issue.

In past 1 month we have seen 3 users impacted. 

Impacted scenario:
From portal.azure.com, user trying to add a new billing role assignment to another user but failed.

Steps:

go to portal.azure.com
open Cost Management + Billing
in left navigation, select Access control (IAM)
Click Add button
Select a billing role
Select or enter an user email then click Add button (here we are using people picker)

### Actual behavior

When user selected a person from NormalPeoplePicker, the persona text is not returned from onChange() callback

### Expected behavior

When user selected a person from NormalPeoplePicker, the selected persona text should be returned from onChange() callback

**Comment by rurikoaraki** [comment]
Hi @yulahyulah, the @fluentui/react package in maintained by https://github.com/microsoft/fluentui/ This is the React Native version of that package. Please post your issue on their GH. Sorry for the confusion!
