### ISSUE TITLE
Tooltips are not accessible which are present in the drop-down menu items while using keyboard.

### ISSUE THREAD

**Issue by msftedad** [microsoft/fluentui-react-native#3515]
### Willing to submit a PR to fix?

- [X] I am willing to submit a PR to fix

### Requested priority

High

### Package version(s)

7.126.0

### OS version(s)

Version 122.0.2365.80 (Official build) (64-bit)

### Platform

- [ ] iOS
- [ ] macOS
- [ ] win32
- [X] windows
- [ ] android

### Please provide a reproduction of the bug

1.Open this URL "[gracious-darwin-lj3zgw - CodeSandbox](https://codesandbox.io/p/sandbox/gracious-darwin-lj3zgw?file=%2fsrc%2findex.js&from-embed=)"
2.Tab till "preview" tab.
3.Tab till Example component dropdown.
4.Observe that "Example Component" menu items "tooltips" is not accessible while using keyboard.

https://github.com/microsoft/fluentui-react-native/assets/93735775/2dfa9ec5-bfea-47a6-a9a1-2713545436c3

### Actual behavior

Tooltips are not accessible which are present in the drop-down menu items while using keyboard.

### Expected behavior

Tooltips should be accessible which are present in the drop-down menu items while using keyboard.

**Comment by rurikoaraki** [comment]
Hi there, the components you're using are authored by https://github.com/microsoft/fluentui, which is the React.js (not React Native) version of this library. Please post any issues you have with their components on that repo.
