### ISSUE TITLE
Button icon prop fails on win32

### ISSUE THREAD

**Issue by tom-un** [microsoft/fluentui-react-native#352]
### Environment Information

- **Package version(s)**: (fill this out, include which package manager you're using)
- **OS version**: (fill this out if relevant)

- **Platform**:
  - [ ] iOS
    - **Xcode version**:
  - [ ] macOS
    - **Xcode version**:
  - [x] win32
  - [ ] windows
  - [ ] android

### Please provide a reproduction of the bug:

Open the test file `apps/fluent-tester/src/RNTester/TestComponents/Button/ButtonIconTest.tsx` and comment out the `  if (Platform.OS !== ('win32' as any)) {` line.

#### Actual behavior:

When the win32 test app is run, the `<Button>` component with an `icon` prop asserts and fails to show the icon.

![win32_button_icon](https://user-images.githubusercontent.com/30053638/88581499-1b044c80-d002-11ea-81bc-781693a3e16b.png)

#### Expected behavior:

No Assertion and the icon appears in the Button.

It works on all other platforms including UWP.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) 
No

Requested priority: (Blocking, High, Normal, Low)

Products/applications affected: (if applicable)

**Comment by FalseLobster** [comment]
Hey @tom-un Thanks for opening this.  We're still refining our triage processes, I just wanted to acknowledge the issue and say that we've put it on our backlog.

**Comment by FalseLobster** [comment]
AB#4421491

**Comment by Saadnajmi** [comment]
@warren-ms does #574 close this?
