### ISSUE TITLE
FluentUI React Native Web Tester Next Steps

### ISSUE THREAD

**Issue by gulnazsayed** [microsoft/fluentui-react-native#397]
#### Platform
- [ ] iOS
- [ ] macOS
- [ ] win32
- [ ] windows
- [ ] android
- [x] web
 
#### Describe the feature that you would like added

1. Look into adding an eslint configuration in the future.
2. We should convert the tester to use FluentUI Text instead of 'react-native' Text and work through the style import bugs. Similarly, solve the StyleSheets import bug with most of the custom components in the tester.
3. Wrap the entire tester in a ThemeProvider so that the theme color doesn't need to be layered on style. This would also facilitate importing themes for the different platforms, apps, and themes when toggled using the dropdown in the header for those three categories.
4. Resolve this Pressability bug. This error occurs when you interact with most test components in the web tester. On this note, some of the test components don't behave the same way they do on the other platform testers due to differences in React Native Web and React Native -- this is definitely something we need to address.
![image](https://user-images.githubusercontent.com/30990970/90182331-caba1800-dd7f-11ea-9eab-e719eff14e13.png)
5. Update test component descriptions and platform statuses. We should probably move the Platform Status definitions from the top of every test component page into a Callout component that renders at the bottom left of the page. We could also change the platform statuses to colored icons instead of words.
6. Fix bugs related to `Callout Test`, `ContextualMenu Test`, `FocusTrapZone Test`, and `Svg Test` so that these tests can render on the web tester.
7. Evaluate production viability of React Native Web and do more research into the differences between React Native Web and React Native.

#### What component or utility would this be added to

FluentUI React Native Web Tester

#### Have you discussed this feature with our team, and if so, who

Tariq Amireh and Jason Morse.

**Comment by rurikoaraki** [comment]
Closing this out as we have decided to not support web endpoint on FURN.
