### ISSUE TITLE
FluentTester looks broken on mobile

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/fluentui-react-native#399]
### Environment Information

- **Package version(s)**: (fill this out, include which package manager you're using)
- **OS version**: (fill this out if relevant)

- **Platform**:
  - [x] iOS
    - **Xcode version**: 11.4.1
  - [ ] macOS
    - **Xcode version**:
  - [ ] win32
  - [ ] windows
  - [ ] android

### Please provide a reproduction of the bug:

The new picker controls for styling do not render properly on iOS. 
The test app in general isn't very mobile friendly, but now the controls get in the way of the content of the page.

![Screen Shot 2020-08-17 at 3 13 03 PM](https://user-images.githubusercontent.com/6722175/90450127-c6eb0600-e09d-11ea-85a6-e101e74b382b.png)
![Screen Shot 2020-08-17 at 3 13 19 PM](https://user-images.githubusercontent.com/6722175/90450129-c8b4c980-e09d-11ea-8dec-cc447509c7e5.png)
![Screen Shot 2020-08-17 at 3 13 22 PM](https://user-images.githubusercontent.com/6722175/90450131-c9e5f680-e09d-11ea-9801-45f444b47f6f.png)

Also, why do we even have a platform control, if the app is rendering on a specific platform to begin with?

#### Actual behavior:

The dropdown is rendered on the top of the screen in full

#### Expected behavior:

Clicking on the drop down would bring up a modal to switch the platform / app / style

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/applications affected: N/A

**Comment by JasonVMo** [comment]
Mobile versions of the tester should use the RNTester style drill-in out pattern rather than a left nav pattern.

**Comment by tido64** [comment]
To be clear, this affects both iOS and Android.

**Comment by Saadnajmi** [comment]
> To be clear, this affects both iOS and Android.

Thanks, we didn't have android at the time of writing. I updated the title.
Worth noting iOS / iPad is particularly egregious because of the large Pickers, which don't function like drop down menus unlike every other platform

**Comment by Saadnajmi** [comment]
#613 Should be a big step to address this.

**Comment by Saadnajmi** [comment]
Closed with #613 and #633
