### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by tkamireh** [microsoft/fluentui-react-native#45]
With a PR our for #24, I'm adding an issue to track documentation work. It would be nice to have a documentation generation system. The API-extractor docs note that for simple cases using the api-documenter package (https://www.npmjs.com/package/@microsoft/api-documenter) may be sufficient.

**Comment by Saadnajmi** [comment]
@ejlayne FYI

**Comment by Saadnajmi** [comment]
We deleted API-Documentor, and are probably not going to use auto generated API documentation. Closing.
