### ISSUE TITLE
Required props on a Slot can't be omitted from render

### ISSUE THREAD

**Issue by FalseLobster** [microsoft/fluentui-react-native#46]
```js
interface IFooSlotProps {
   root: { someRequiredString: string; someOptionalString?: string };
}

export const MyFooComponent = compose<IFooProps, IFooSlotProps>({
    ...restOfComposeOptions,
    render: (Slots: ISlots<IFooSlotProps>, data: IFooRenderData, ...children: React.Component[]) : JSX.Element => { 
        return <Slots.root />
    }
})
```

In the example above the JSX for `<Slots.root />` fails to compile because it's missing someRequiredString, even though it should have been baked into the slot props as part of usePrepareProps.

Jason suggested fixing this might be as simple as adding a `Partial<>` around `TProps` in `_createSlotRenderFunction`

**Comment by rurikoaraki** [comment]
Not sure if this is a bug anymore as I don't remember running into this recently. Closing out, feel free to reopen if this is still an issue.
