### ISSUE TITLE
Xcode tab stops don't match github tab stops

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/fluentui-react-native#523]
### Environment Information

- **Package version(s)**: (fill this out, include which package manager you're using)
- **OS version**: (fill this out if relevant)

- **Platform**:
  - [x] iOS
    - **Xcode version**: 12.0
  - [x] macOS
    - **Xcode version**: 12.0
  - [ ] win32
  - [ ] windows
  - [ ] android

### Please provide a reproduction of the bug:

FURN thinks tab width is 2. Xcode thinks it's 4. Github thinks it's.. something else. We should rectify this so I don't get "nit: spacing" in my PR's. Probably done by adding a .editorconfig file.

What I said in #482 
> First line uses a tab, rest of the lines uses spaces assuming tab width is 2 spaces. I think github assumes a different tabwidth. I looked into what we could do to address that, and maybe we could add a .editorconfig https://stackoverflow.com/questions/8833953/how-to-change-tab-size-on-github/23522945#23522945

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Low

Products/applications affected: None

**Comment by HeyImChris** [comment]
Can you not change the Xcode preferences to match it?
![Uploading Screen Shot 2020-10-23 at 10.37.24 PM.png…]()

**Comment by Saadnajmi** [comment]
I got it: GitHub thinks tabs are 8 spaces wide. So, even if I change my own preference in Xcode, FURN and Github are in disagreement. Better solution may be for me to use spaces in xcode... which makes me sad but whatever :D 
And also add a .editorconfig so FURN and github are in agreement
