### ISSUE TITLE
Published packages are not providing the files which the sourcemaps link to

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/fluentui-react-native#546]
### Please provide a reproduction of the bug:

Packages are being published with sourcemap information pointing to files which are not published as part of the npm package.  The ts files should be included in the published package so that the sourcemap files are useful.

NonErrorEmittedError: (Emitted value instead of an instance of Error) 
Cannot find source file `../../src/NativeModule/fallbackOfficeModule.ts`:
Error: Can't resolve `../../src/NativeModule/fallbackOfficeModule.ts` in `..\node_modules\@fluentui-react-native\win32-theme\lib\NativeModule`

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/applications affected: (if applicable)

**Comment by tkamireh** [comment]
Are the files in question source from deeper dependencies? Looks like generated sourcemaps are pointing to relative paths that may not be valid depending on the location of the deeper dep.

**Comment by acoates-ms** [comment]
I think the paths are only relative within the single package.  In this case the reference is from `@fluentui-react-native\win32-theme\lib\NativeModule\index.js.map` is referencing `../../src/NativeModule/index.ts` which would be `@fluentui-react-native\win32-theme\src\NativeModule\index.ts` -- which isn't published.

**Comment by tkamireh** [comment]
Ah our npmignores are all over the place (ignoring too much or nothing at all. [Example here](https://github.com/microsoft/fluentui-react-native/blob/master/packages/theming/win32-theme/.npmignore)

**Comment by FalseLobster** [comment]
AB#4828213

**Comment by Saadnajmi** [comment]
Closed with #643 ?
