### ISSUE TITLE
Hook up documentation generation

### ISSUE THREAD

**Issue by JasonVMo** [microsoft/fluentui-react-native#6]
An attempt at this was done in the documentation folder using docz but it seems highly unstable and doesn't actually work.  We should find some solution, likely involving gatsby, to do auto documentation.

Ideally this also includes support for mdx files.

**Comment by FalseLobster** [comment]
@PPatBoyd What's your take on this Issue?

**Comment by PPatBoyd** [comment]
Our public-facing docs are run out of the fluent repo -- we can set up an auto-doc pipeline to that, but inevitably need to manually manage a fair amount of content in that repo (examples, etc).  There was an attempt pre-Build to set up a new website that would've let us host most of the documentation content in this repo, but that effort lost traction and has been abandoned (i.e. not fixing what works "well enough").  Any rigor we apply to documentation quality will be in the manually managed portion of the docs, autodoc can pull API information but I don't see more than that on the horizon.

**Comment by FalseLobster** [comment]
So for auto-docing APIs we already have #45 .  If PRs to the fluentui repo is our POR for our manual doc process, can we close this?  Is this item still relevant?  @PPatBoyd @JasonVMo

**Comment by PPatBoyd** [comment]
@FalseLobster I would say we can close it -- feel free to re-open :)
