### ISSUE TITLE
Tabbing via Keyboard into RadioGroup incorrectly selects first RadioButton instead of currently selected RadioButton

### ISSUE THREAD

**Issue by ejlayne** [microsoft/fluentui-react-native#604]
### Environment Information

- **Package version(s)**: (fill this out, include which package manager you're using)
- **OS version**: (fill this out if relevant)

- **Platform**:
  - [ ] iOS
    - **Xcode version**:
  - [ ] macOS
    - **Xcode version**:
  - [x ] win32
  - [ ] windows
  - [ ] android

### Please provide a reproduction of the bug:

1. Open FluentUI Tester
2. Go to RadioGroup Test page
3. Using your mouse, select "Option B" in the "Uncontrolled RadioGroup" section.
4. Now keyboard tab through the entire rest of the UI until it comes back to "Uncontrolled RadioGroup", and observe RadioGroup selected item.

#### Actual behavior:

When you tab back into the RadioGroup, focus goes to the first RadioButton "Option A", and the "Option A" RadioButton gets selected, even if "Option B" was previously selected.

#### Expected behavior:

When you tab back into the RadioGroup, keyboard focus should go to the selected RadioButton, and not change what RadioButton is selected.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/applications affected: WIn32 Office

**Comment by ksiler** [comment]
AB#4901910
