### ISSUE TITLE
@fluentui-react-native/button has a hardcoded specific dependency on react-native-win32

### ISSUE THREAD

**Issue by acoates-ms** [microsoft/fluentui-react-native#608]
@fluentui-react-native/button has a hardcoded specific version of react-native-win32 as a dependency.  I think this should be a devDependency?  Or it shouldn't be so specific. 

https://github.com/microsoft/fluentui-react-native/blob/1dc161d4e6ea471c3bcb1bdfec3e6f7a9e94b7a5/packages/components/Button/package.json#L30

**Comment by Saadnajmi** [comment]
I noticed this when I first attempted moving the repo to 0.63. I think what could work is having it be a peer dependency, and moving the win32 specific code to a .win32.tsx file

**Comment by tkamireh** [comment]
AB#4903325

**Comment by Saadnajmi** [comment]
I think this was fixed with #631 ?
