### ISSUE TITLE
Doc Error: Path for web debugging looks wrong

### ISSUE THREAD

**Issue by pruthvip** [microsoft/fluentui-react-native#618]
### Environment Information

- **Package version(s)**: (fill this out, include which package manager you're using)
- **OS version**: (fill this out if relevant)

- **Platform**:
  - [ ] iOS
    - **Xcode version**:
  - [ ] macOS
    - **Xcode version**:
  - [x] win32
  - [ ] windows
  - [ ] android

### Please provide a reproduction of the bug:
https://github.com/microsoft/fluentui-react-native/blob/master/apps/win32/README.md

Is the 5th step given for Debug FluentUI Tester app with web debugging, correct. What is the location `experiments\tester` or its a typo ?

**Comment by ksiler** [comment]
This must have been an older location. The correct location is under `apps\win32`. I've created a PR to update it. Thanks for the catch!
