### ISSUE TITLE
FluentTester doesn't expand to fill screen on mobile

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/fluentui-react-native#623]
[Microsoft Internal ADO Bug](https://office.visualstudio.com/APEX/_backlogs/backlog/FX/Features/?workitem=4919889)

### Environment Information

- **Package version(s)**: (fill this out, include which package manager you're using) 
- **OS version**: (fill this out if relevant)
- **Platform**:
  - [x] iOS
    - **Xcode version**: 12.4
  - [ ] macOS
    - **Xcode version**:
  - [ ] win32
  - [ ] windows
  - [x] android

### Please provide a reproduction of the bug:

![Screen Shot 2021-03-01 at 10 54 47 PM](https://user-images.githubusercontent.com/6722175/109862546-2ec20200-7c26-11eb-91ca-dde58db41393.png)

FluentTester on iOS (and probably Android) doesn't grow to fill the whole screen. This is because <FluentTesterApp> is wrapped in a SafeAreaView on both platforms that doesn't specify `flex: 1` in their style. Adding that let's the SafeAreaView grow, and thus the child FluentTester view grow. 

We can either add the style specifically on iOS and Android, or if SafeAreaView is a no-op on desktop, just always wrap <FluentTester> in a <SafeAreaView>.

### Priorities and help requested:

Are you willing to submit a PR to fix? **Yes**

Requested priority: **Normal**

Products/applications affected: (if applicable)

**Comment by Saadnajmi** [comment]
@tamasane is this an issue on Android too?

**Comment by tamasane** [comment]
> @tamasane is this an issue on Android too?

For Android, the following styles in FluentTester.tsx resolved this issue:

```
const getThemedStyles = themedStyleSheet((t: Theme) => {
  return {
    root: {
      backgroundColor: t.colors.background,
      height: '100%',
      flexDirection: 'column',
      justifyContent: 'flex-start',
      alignItems: 'stretch',
      padding: 4,
    },
  };
});
```

**Comment by Saadnajmi** [comment]
@tamasane Thanks! I've got a fix with similar styling I'll send out soon. I just want to test on windows first. Works on every other platform though :)
