### ISSUE TITLE
NuGet Pipeline broken

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/fluentui-react-native#632]
https://github.com/microsoft/fluentui-react-native/commit/5300d6216a2375d11810f1e4762774b48a922e04

With that commit, I think we changed the names of the bundles, and our Publish pipeline is failing because it can't find the bundles. Nothing uses those bundles yet and the NPM Publish pipeline still runs so this isn't too bad.

**Comment by harrieshin** [comment]
@afoxman can you help address this regression?

**Comment by afoxman** [comment]
Definitely. Got a link to the pipeline? And any tips on running bundling locally so I can test my fix?

**Comment by afoxman** [comment]
ADO Pipeline: https://dev.azure.com/ms/ui-fabric-react-native/_build?definitionId=229

Advice on testing -- use the PR loop to run nuget packaging. no command-line scripts for running packaging.

**Comment by HeyImChris** [comment]
@afoxman you can also manually queue up either pipeline to run on any given commit if there's reason to believe it might fail. Not an ideal solution but with the current setup that should save some time and let you test a bit more quickly.

What do you mean by "no command-line scripts for running packaging"? Is all CI not run through command-line scripts?

**Comment by Saadnajmi** [comment]
@HeyImChris I spoke with @afoxman offline on the best approach. What he means is there is no local script to bundle the NuGet package / do the equivalent of the Publish pipeline. It's a good followup to add that (like what we have in FluentUI Apple and what I'm currently adding to SDX Platform)

**Comment by afoxman** [comment]
Fixed by #640

**Comment by Saadnajmi** [comment]
Thanks for taking this on!
