### ISSUE TITLE
Use the Community Module Picker in FluentTester

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/fluentui-react-native#639]
FluentTester uses the React Native Core Picker. This is deprecated, and will eventually be removed. We should use the community module picker. That has the additional complexity of linking the native module (auto linking won't work bc it's a transitive dependency), so we either need to combine the platform specific test apps into one big test app and use auto linking, or link it manually per platform. We've already linked it for macOS and iOS.

Win32 can't use the community module, so we'll keep using core there.

- **Platform's done**:
  - [x] iOS
  - [x] macOS
  - [ ] windows
  - [ ] android

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/applications affected: (if applicable)

**Comment by rurikoaraki** [comment]
Fixed with #1762
