### ISSUE TITLE
Fluent Tester on Win32 does not get keyboard focus initially

### ISSUE THREAD

**Issue by ejlayne** [microsoft/fluentui-react-native#674]
### Environment Information

- **Package version(s)**: (fill this out, include which package manager you're using)
- **OS version**: (fill this out if relevant)

- **Platform**:
  - [ ] iOS
    - **Xcode version**:
  - [ ] macOS
    - **Xcode version**:
  - [x ] win32
  - [ ] windows
  - [ ] android

### Please provide a reproduction of the bug:

1. git pull, yarn, yarn build, cd apps/win32, yarn bundle, yarn run-win32
2. Win32 Tester launches
3. Hit Tab on keyboard, and continue hitting Tab

#### Actual behavior:

No-op, do not see keyboard focus moving between components when I hit Tab. Have to alt tab and then alt tab back to get focus into app for keyboarding to work. 

Possibly a bug with Fluent Button component. However, it looks like focus wants to start on the "Theme: Default" dropdown component, but when I alt-tab/alt-tab-back into the app, and then hit tab, it looks like focus flickers on Theme: Default for a split second before moving to Light/Dark: Auto's dropdown.

#### Expected behavior:

Keyboard focus visibly moves between buttons and interactable elements in Fluent Tester. Expect this to work when I originally launch the Fluent Tester, as focus should go somewhere.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/applications affected: Just Fluent Tester, but want to make sure it isn't a bug with Fluent Button.

**Comment by ksiler** [comment]
Linking this bug from ADO: AB#5099897

It's possible they're the same bug

**Comment by ejlayne** [comment]
@ksiler looks like the linked bug is closed. Can we close this issue too?

**Comment by ksiler** [comment]
@ejlayne Sorry, I should have followed up here. The bug I linked above is unrelated to this issue. This bug seems to be the same: AB#5127814

**Comment by ksiler** [comment]
Closing this issue. Bug has been resolved.
