### ISSUE TITLE
Demo project

### ISSUE THREAD

**Issue by mannyquick12** [microsoft/fluentui-react-native#711]
This might not be a serious issue, but I would love to see a full demo project built with it. Some of course are still in the learning curve🙏🏼. Maybe some links to some other repos?

**Comment by Saadnajmi** [comment]
We have a series of test apps for every platform under `apps`, I.E: `apps/macos , apps/android, apps/windows` ...
They all share common JS: `apps/fluent-tester`. Does that help?
