### ISSUE TITLE
FluentUI Tester: "Office" Theme, "Dark" option does not do anything

### ISSUE THREAD

**Issue by ejlayne** [microsoft/fluentui-react-native#721]
### Environment Information

- **Package version(s)**: 0.23.12
- **OS version**: Windows 10

- **Platform**:
  - [ ] iOS
    - **Xcode version**:
  - [ ] macOS
    - **Xcode version**:
  - [x ] win32
  - [ ] windows
  - [ ] android

### Please provide a reproduction of the bug:

1. Launch FluentUI Tester Win32: ...\fluentui-react-native\apps\win32 yarn run-win32
2. Click on Button Test in the left set of test pages to open the Button test page.
2. At the top of the Tester, choose Theme: "Office". In the Light/Dark option, "Light" should be chosen by default.
3. Then choose Light/Dark: "Dark". Observe any changes in the Tester's UI or the Button test page.

#### Actual behavior:

There are no visual changes, outside of a subtle flash (UI refresh?).

#### Expected behavior:

The Dark theme should be applied to the app and the test page. A Dark theme is correctly applied or Theme: "Default" and "Caterpillar". This is problematic because the Tester currently defaults to having the "Office" theme selected.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/applications affected: Fluent UI Tester, unless something is wrong with our Office Theme in Win32.

**Comment by rurikoaraki** [comment]
I'll take a look! But just so you know, "This is problematic because the Tester currently defaults to having the "Office" theme selected." is being fixed with https://github.com/microsoft/fluentui-react-native/pull/716. The change to Office instead of Default theme in the tester was a mistake.

**Comment by rurikoaraki** [comment]
Closing out as not high priority
