### ISSUE TITLE
Add Box to ThemeProvider

### ISSUE THREAD

**Issue by FalseLobster** [microsoft/fluentui-react-native#75]
The Fabric Web folks have a Box in their ThemeProvider to apply the background color to the region covered by the ThemeProvider.  It seems like we might want to do this as well with a View.  See ThemeProvider and Box here:

https://github.com/microsoft/fluent-ui-react-staging/tree/master/packages/react-theming/src/components

**Comment by rurikoaraki** [comment]
This seems to be an outdated issue. I'm not sure if this is still wanted/needed.

Going to close this in a few days if there's no objection. Feel free to reopen if you disagree
