### ISSUE TITLE
Shimmer breaks in light mode

### ISSUE THREAD

**Issue by chiuam** [microsoft/fluentui-react-native#751]
### Environment Information

- **Package version(s)**: 0.17.3
- **OS version**: Big Sur 11.3.1

- **Platform**:
  - [X] iOS
    - **Xcode version**:
  - [X] macOS
    - **Xcode version**:
  - [ ] win32
  - [ ] windows
  - [X] android

### Please provide a reproduction of the bug:
Shimmer is not showing the correct tint colors in light mode
#### Actual behavior:

![image](https://user-images.githubusercontent.com/67026167/123710991-aa7f3480-d83d-11eb-8251-d352fdf4dcc6.png)

#### Expected behavior: 
Gradient tint color should be `white` and background color should be `#E1E1E1` in light mode.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low) Normal

Products/applications affected: N/A, shimmer is not being used in prod yet

**Comment by Saadnajmi** [comment]
This changed after I removed the native theming module, which had a slight difference in that it reported either 'light' or 'dark' for the theme appearance while the JS just reports 'dynamic'.
Working on a fix.
