### ISSUE TITLE
Omitting a slot from the StyleFactories drops settings from from the final slotprops

### ISSUE THREAD

**Issue by FalseLobster** [microsoft/fluentui-react-native#76]
Adopting the new versions of @uifabricshared libraries forced me to introduce this work around to some components:

```ts
compose(
  ...otherstuff,
  settings,
  slots: {
    root: ReactNative.View,
    content: ReactNative.Text
  },
  styles: {
    root: [],        // Empty array 
    content: [foregroundColorTokens, textTokens]
  }
);
```

Without the empty array of style operations, the root slot settings get dropped from the final slot props.

**Comment by rurikoaraki** [comment]
Closing this as it's for the older compose framework which is now deprecated.
