### ISSUE TITLE
Crash in RCTText if fontSize is 0 when on react-native-windows 0.63

### ISSUE THREAD

**Issue by tido64** [microsoft/fluentui-react-native#765]
While investigating a crash in the [PR migrating the Windows test app](https://github.com/microsoft/fluentui-react-native/pull/755) to `react-native-test-app`, I found that `RCTText` no longer accepts `fontSize` set to 0.

### Environment Information

- **Package version(s)**: `master`
- **OS version**: Windows 10 Enterprise 21H1 19043.1083

- **Platform**:
  - [ ] iOS
    - **Xcode version**:
  - [ ] macOS
    - **Xcode version**:
  - [ ] win32
  - [x] windows
  - [ ] android

### Please provide a reproduction of the bug:

1. Check out this branch: https://github.com/microsoft/fluentui-react-native/pull/755
2. Build and run windows test app
    ```sh
    yarn
    yarn build
    cd apps/windows
    yarn install-windows-test-app
    start windows/FluentTester.sln
    yarn start
    ```
3. Once the app starts, click on the Persona tab

#### Actual behavior:

![image](https://user-images.githubusercontent.com/4123478/124778869-9922e000-df41-11eb-9f73-79816b6a0d27.png)

A workaround is to explicitly set font size on all tokens:

```diff
diff --git a/apps/fluent-tester/src/FluentTester/TestComponents/Persona/StandardUsage.tsx b/apps/fluent-tester/src/FluentTester/TestComponents/Persona/StandardUsage.tsx
index f89ba921..3efd13c4 100644
--- a/apps/fluent-tester/src/FluentTester/TestComponents/Persona/StandardUsage.tsx
+++ b/apps/fluent-tester/src/FluentTester/TestComponents/Persona/StandardUsage.tsx
@@ -45,6 +44,14 @@ export const StandardUsage: React.FunctionComponent<{}> = () => {
   const [showOptional, setShowOptional] = React.useState(true);
   const [imageSize, setImageSize] = React.useState<PersonaSize | undefined>('size72');

+  const PersonaFix = Persona.customize({
+    tokens: {
+      textFont: { fontSize: 23 },
+      secondaryFont: { fontSize: 20 },
+      tertiaryFont: { fontSize: 17 },
+      optionalFont: { fontSize: 14 },
+    },
+  });
+
   return (
     <View style={commonStyles.root}>
       {/* settings */}
@@ -67,7 +74,7 @@ export const StandardUsage: React.FunctionComponent<{}> = () => {
         </Picker>
       </View>

-      <Persona
+      <PersonaFix
         text={showPrimary ? 'Rajesh Jha' : undefined}
         secondaryText={showSecondary ? 'Executive Vice President' : undefined}
         tertiaryText={showTertiary ? 'E & D' : undefined}
```

#### Expected behavior:

It doesn't crash.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

**Comment by tido64** [comment]
cc @Saadnajmi, @ejlayne, @samuelfreiberg

**Comment by Saadnajmi** [comment]
Looking at `Persona.helpers.ts`, we do indeed set a lot of the font sizes to 0:

``` 
const tertiaryFontTable: IPersonaFontTable = {
  size8: { fontSize: 0 },
  size24: { fontSize: 0 },
  size32: { fontSize: 0 },
  size40: { fontSize: 0 },
  size48: { fontSize: 0 },
  size56: { fontSize: 0 },
  size72: { fontSize: 'secondary' },
  size100: { fontSize: 'secondary' },
  size120: { fontSize: 'secondary' },
};

const optionalFontTable: IPersonaFontTable = {
  size8: { fontSize: 0 },
  size24: { fontSize: 0 },
  size32: { fontSize: 0 },
  size40: { fontSize: 0 },
  size48: { fontSize: 0 },
  size56: { fontSize: 0 },
  size72: { fontSize: 0 },
  size100: { fontSize: 'secondary' },
  size120: { fontSize: 'secondary' },
};
```

This feels like it was a bug / hack to get those two text fields to not show up at certain sizes. I'm inclined to say we should raise the bug with `react-natine-windows`, but also we should get rid of these empty font sizes from the `Persona` component.

**Comment by Saadnajmi** [comment]
(Or to quickly unblock things, remove the Persona Test page from `apps/fluent-tester/src/FluentTester/testPages.windows.ts`. I would only do that to unblock testing the rest of #755 though

**Comment by tido64** [comment]
> (Or to quickly unblock things, remove the Persona Test page from `apps/fluent-tester/src/FluentTester/testPages.windows.ts`. I would only do that to unblock testing the rest of #755 though

I still have to investigate other pages. The RadioGroup and Text pages just blank out for some reason.

**Comment by Saadnajmi** [comment]
RadioGroup depends on FocusZone, which is a win32 only native module. We're bringing FocusZone to macOS, but that will definitely fail. 
Text probably has a reference to a font that doesn't exist on windows. We had to special case some of those fonts for apple, and maybe need to do the same for windows
