### ISSUE TITLE
Repo should be called `fluent-ui-react-native`

### ISSUE THREAD

**Issue by soettl** [microsoft/fluentui-react-native#81]
This repo should be called `fluent-ui-react-native` for consistency with the `fluent-ui-react` sister repo (not `fluentui-react-native`).

**Comment by soettl** [comment]
If that is so, then the other repo should be renamed to `fluentui-react`

**Comment by FalseLobster** [comment]
Names are hard...   the ReactJS component library is now called https://github.com/microsoft/fluentui

no `-react` but also no extra hypen in `fluentui` hopefully that's close enough? :)
