### ISSUE TITLE
Icon color not working correctly

### ISSUE THREAD

**Issue by lindaweng** [microsoft/fluentui-react-native#888]
### For SVGs:
Icon color is currently being finally set within the `renderSvg` call. There, it is pulling the color from `svgIconProps.color` which is the same as `iconProps.svgSource.color`. In actuality, color is being passed in at `iconProps.color`. So `svgIconProps.color` is always undefined and thus the color of the icon defaults to white or black depending on light/dark mode
By changing `svgIconProps.color` to `iconProps.color`, the color that users pass in gets recognized and works. However, in the call to make the Icon, if the user doesn't pass in a color, the color that gets passed to `renderSvg` is `theme.colors.buttonText`. (Minor change there, in Icon component creation, `props.color` should be `rest.color` as `rest` is the most updated passed in props at that point.) This works fine for default or ghost buttons but for primary and fab styled buttons this causes the icon to blend in with the background.
For experimental button, the icon is set with a `tintColor` style which tints it to the accurate color for each button. To pull this color within Icon, it should be `iconProps.style.tintColor`. However, if we pull this color, we do not pull the color that the user passes in so the user is unable to customize the color of the icon. Also, the non-experimental button does not set a tint color so all icons in those buttons will be white/black depending on light/dark mode.

### For raster image (PNG) icons:
`tintColor` accurately tints the icon to the correct color. Currently icons in the non-experimental button are not being tinted to any color so they appear as their natural base color. There is no need to change any code.

### For font icons:
Similar to SVG icons in the fact that changing `iconProps.color` to `iconProps.style.tintColor` in `renderFontIcon` tints the icon to the appropriate color but ignores custom colors. Currently the icons blend into the background for fab and primary styled buttons.

### The fix:
The icon should check if the user passed in a color, if so, use that color. If the user did not pass in a color, check if a tint color exists. If it does, use the tint color. Finally if the tint color does not exist, then default to black/white depending on light/dark mode.
Also, adding a `tintColor` style prop to the icon in the non-experimental button may be nice so that the icons match the button theme if a custom color is not passed in.

### Current coloring:
Experimental button
<img width="123" alt="Screen Shot 2021-08-11 at 2 40 17 PM" src="https://user-images.githubusercontent.com/30802320/129107659-9a27e79f-05b9-4daa-a361-6671d2ecb364.png">
Non-experimental button
<img width="179" alt="Screen Shot 2021-08-11 at 2 41 09 PM" src="https://user-images.githubusercontent.com/30802320/129107694-d1f623ce-3e65-4719-af79-398a34f45a71.png">

**Comment by rurikoaraki** [comment]
Underlying issue is that RN SVG doesn't support the new ColorValue: https://github.com/react-native-svg/react-native-svg/issues/1391 If it did, then this would be easy to fix.

In the meantime we'll probably have to put in some conversion logic from ColorValue to string in order to make this work correctly.
