### ISSUE TITLE
Android Experimental Button PNG Icon not showing up

### ISSUE THREAD

**Issue by lindaweng** [microsoft/fluentui-react-native#892]
On android within the experimental button test, the PNG/raster image icons are not showing up. There is space created for them, but the icon isn't there.
PNG icons seem to work on the android platform in general as the PNG icon in the button test shows up. The PNG icon in the experimental button passes the same properties as the one in button test so the difference is confusing.

<img width="377" alt="Screen Shot 2021-08-12 at 3 12 40 PM" src="https://user-images.githubusercontent.com/30802320/129276662-c35ce454-cbde-42ba-80c7-d6cda13ff98b.png">

**Comment by rurikoaraki** [comment]
"Experimental Button" is now just "Button" and can be found under the "Button Test" page. We still have the deprecated Button lying around but will move away from it eventually.
