### ISSUE TITLE
Android Brand color naming does not match Apple naming

### ISSUE THREAD

**Issue by lindaweng** [microsoft/fluentui-react-native#893]
Apple brand colors were recently renamed to use prefix `branded` instead of `brand`. (https://github.com/microsoft/fluentui-react-native/pull/883) Android colors are still named with prefix `brand`. This causes color bugs if something is set to `brandedBackground` for example. The correct color would show up on iOS and macOS, but the correct color would not show up on Android as it doesn't know what `brandedBackground` is.
This is seen in the Experimental Button test with primary styled buttons (including FAB).

With `branded`. This is what it currently looks like.
<img width="393" alt="Screen Shot 2021-08-12 at 3 16 48 PM" src="https://user-images.githubusercontent.com/30802320/129277046-d5efd7a9-ea20-4db7-ba1c-f03d11a297b4.png">

With `brand`. This is what it should look like.
<img width="395" alt="Screen Shot 2021-08-12 at 3 17 35 PM" src="https://user-images.githubusercontent.com/30802320/129277105-9dad2e3d-918c-4ef9-947b-3602b55c876c.png">

**Comment by Saadnajmi** [comment]
@rurikoaraki Was this also fixed with your last PR?

**Comment by rurikoaraki** [comment]
@Saadnajmi Yeah #896 should have fixed this
