### ISSUE TITLE
Bump react-native-test-app to 0.7.2 for Expander

### ISSUE THREAD

**Issue by amdingler** [microsoft/fluentui-react-native#894]
### Environment Information

- **Platform**:
  - [ ] iOS
    - **Xcode version**:
  - [ ] macOS
    - **Xcode version**:
  - [ ] win32
  - [x] windows
  - [ ] android

### Please provide a reproduction of the bug:
Launch the window test application. Go to the Expander page.

#### Actual behavior:
The app crashes when the Expander page is selected.

#### Expected behavior:
When you go to the Expander page in the windows test app, the page should render with Expanders displayed.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/applications affected: Windows test app

### Notes
The Expander is backed by a WinUI 2.6 control, so the test application needs to support XAML 2.6.0. react-native-test-app was bumped to this version of XAML in 0.7.2, so updating this will provide the correct version of XAML.

**Comment by rurikoaraki** [comment]
@chiuam We're bumped RN tester past 0.7.2 and the Expander test still isn't working, do you know if is there's anything else we need to do to get it to show?

**Comment by Saadnajmi** [comment]
I don't remember the specific details (I was the one in most contact with Anna who wrote the control). Perhaps @chrisglein or @rectified95 (her intern manager / mentor respectively) remember?

**Comment by rurikoaraki** [comment]
Whoops my bad @chiuam for some reason I thought you opened this issue. Sorry about that!

**Comment by Saadnajmi** [comment]
Expander still doesn't work, and I'll close this and continue tracking with #1027

**Comment by rectified95** [comment]
fyi @amdingler

**Comment by Saadnajmi** [comment]
To clarify, I think It works in a standalone test app, but not in our FluentTester. And I also believe @tatianakapos has taken it over. I was just doing some bookkeeping as I recently touched the Expander test in FluentTester once more =)
