### ISSUE TITLE
"Pivot" is not a term recognized by the UX community for a tab

### ISSUE THREAD

**Issue by ux2uidesign** [microsoft/fluentui-react-native#921]
#### Platform
- [ ] iOS
- [ ] macOS
- [ ] win32
- [ ] windows
- [ ] android
 
#### Describe the feature that you would like added

Hello, please remove all references to "pivots" when referring to tabs. Do not make up names for universally accepted names of controls. If this is not the right department, please refer me to the correct team's contact information. Thank you.

**Comment by Saadnajmi** [comment]
wait, is this a bot or a real person?
