### ISSUE TITLE
Add an adapter for macOS

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/fluentui-react-native#932]
#### Platform
- [ ] iOS
- [x] macOS
- [ ] win32
- [ ] windows
- [ ] android
 
#### Describe the feature that you would like added

FURN uses it's `adapters` package to filter out props to only what applies to a platform, so android doesn't get win32 props, etc. It is currently missing a macOS adapter, so as it is, if a component uses IViewProps, it may not get macOS specific props like `enableFocusRing / tooltip / nextKeyView`. Moreover, the default `adapters.ts` files uses win32 props, so components on macOS are also getting win32 props. We should fix this by just adding a macOS specific adapter.

#### What component or utility would this be added to

Components that currently use IViewProps:

- Button
- Checkbox
- FocusTrapZone (not implemented on macOS)
- Link
- Persona
- PersonaCoin
- Pressable
- Tabs

Theoretically all components that inherit from View should be using IViewProps though.

#### Have you discussed this feature with our team, and if so, who

Nope, filing this bug is how I intend to.

**Comment by Saadnajmi** [comment]
Bug internally in our ADO Instance: https://office.visualstudio.com/APEX/_workitems/edit/5365221

**Comment by chiuam** [comment]
fixed with https://github.com/microsoft/fluentui-react-native/pull/1017
