### ISSUE TITLE
Pipeline Apple PR ios  - yarn ios

### ISSUE THREAD

**Issue by dake3601** [microsoft/fluentui-react-native#974]
### Environment Information

- **Platform**:
  - [x] iOS
    - **Xcode version**:
  - [ ] macOS
    - **Xcode version**:
  - [ ] win32
  - [ ] windows
  - [ ] android

### Please provide a reproduction of the bug:

PR #972 failed exited "yarn ios" with an error in 5 seconds, even though changes where close to null.

#### Actual behavior:

Example 1:
![image](https://user-images.githubusercontent.com/57121448/131930767-6c2e5fb8-10ba-403c-b25c-49c2576fe53a.png)

Example 2:
![image](https://user-images.githubusercontent.com/57121448/131930996-b2d36f92-1a3d-4530-8bcd-cc9827d31ce8.png)

#### Expected behavior:

yarn ios should not be crashing after less than 10 seconds.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/applications affected: N/A

**Comment by Saadnajmi** [comment]
closed with #988
