### ISSUE TITLE
Height of the Button and Link components increases with adding borderWidth

### ISSUE THREAD

**Issue by ValentinaKozlova** [microsoft/fluentui-react-native#986]
- **Platform**:
  - [ ] iOS
  - [ ] macOS
  - [X] win32
  - [ ] windows
  - [ ] android

### Steps to reproduce:
1. Height should be set for the Button or Link component.
2. Increase borderWidth for these components.
Example:
![image](https://user-images.githubusercontent.com/11574680/132379950-38e8c880-9ca8-4c7a-a65f-ead7c1f3ee8e.png)
Button with focus has bigger height:
![image](https://user-images.githubusercontent.com/11574680/132380025-e3b5cfef-8ab5-4994-805c-f6a71878f140.png)

#### Actual behavior:
Height increases.

#### Expected behavior:
Height should stay the same.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes, temporary solution
Requested priority: Normal

**Comment by rurikoaraki** [comment]
Focus visuals are now implemented, this shouldn't be an issue anymore. Feel free to reopen if this is causing any issues
